### ISSUE TITLE
Fix the bug of subjects alloted to teachers

### ISSUE THREAD

**Issue by Chirag4904** [Chirag4904/timetable#84]
Once the teacher is assigned a subject it is stored in alloted Subject array so if the subject is removed from that teacher then the hours are updated to 0 but the object still remains in alloted subjects which is taken by ui and displayed.
![image](https://user-images.githubusercontent.com/48693268/202422481-cd739742-989d-48ee-876b-16ce1ef7fe1d.png)

**Comment by Chirag4904** [comment]
@RoguedBear I am wondering if it should be handled in frontend or backend.
In frontend side I can just add additional checks if all L,T,P hours are equal to 0 then it will not be displayed.
Alternatively if in the backend we check if the L,T,P becomes 0 for that alloted subject then that subject should be removed from the allotedSubjects array for that teacher.
What do you think?

**Comment by RoguedBear** [comment]
ideally this should be handled in the backend, when you call the delete subject api, the backend takes care of all the places to delete that teacher from

**Comment by Chirag4904** [comment]
Ok let's see if it's too much hassle for now then we will do it in frontend and keep this issue open otherwise fix it in the backend.

**Comment by RoguedBear** [comment]
completed in #106
